import java.time.LocalDateTime;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;


public class FrmPrincipal extends javax.swing.JFrame {

    private Inventario inventario = ControlInventario.getInventario();
    private FrmBusqueda frmBusque;
    public FrmPrincipal(Inventario inventario) {
        initComponents();
        

        this.inventario = inventario;
        inicializarTabla();
        actualizarComboCategoria();
        mostrarInventario();
        cboxCategoria.setSelectedIndex(0);
    }
    private void inicializarTabla() {
    String[] columnas = {"Nombre del Producto", "Precio", "Cantidad","Categoria","Tipo","Descripcion","fecha registro/actualiz."};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);
    tablaInventario.setModel(modelo);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboxCategoria = new javax.swing.JComboBox<>();
        txtdescripcion = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnAgregar2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Panel De Botones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 247, -1));

        txtNombre.setForeground(new java.awt.Color(0, 0, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 490, 60));

        txtPrecio.setForeground(new java.awt.Color(0, 0, 255));
        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 490, 60));

        txtCantidad.setForeground(new java.awt.Color(0, 0, 255));
        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 490, 63));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 110, 50));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 130, 50));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 100, 50));

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaInventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1090, 291));

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 120, 50));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-icon-images-2 (1).jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        cboxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONA---", "Audifono", "Mouse", "Parlante", "Teclado", "Cargador", "Mica", "Tripode", "Pantalla", "Bateria", "Altavoz" }));
        cboxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cboxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cboxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 490, 76));

        txtdescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 490, 74));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 120, 50));

        btnEliminar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar2.setText("Eliminar");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 90, 50));

        btnAgregar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar2.setText("Agregar");
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 50));

        btnEditar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar2.setText("Editar");
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 90, 50));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de Inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 480, 190));

        cboxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONA---", "Producto", "Repuesto" }));
        cboxTipoProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        getContentPane().add(cboxTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 490, 70));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 450, 90));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Registro de Productos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 247, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 1.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 1.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 1.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, -1, -1));

        setSize(new java.awt.Dimension(1120, 875));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        txtNombre.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtdescripcion.setText("");
        cboxCategoria.setSelectedIndex(0);
        cboxTipoProducto.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    private void mostrarInventario(){
        DefaultTableModel modelo = (DefaultTableModel) tablaInventario.getModel();
        modelo.setRowCount(0); // Limpia filas previas
        List<Producto> productos = inventario.getListaProductos();
        
        for (Producto p : productos) {
        Object[] fila = {p.getNombre(), p.getPrecio(), p.getCantidad(),p.getCategoria(),p.getTipoProducto(), p.getDescripcion(),p.getFecha()!=null ? p.getFecha().toString():""};
        modelo.addRow(fila);
        }
   }
    
   
     
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String precio = txtPrecio.getText();
        String cantidad = txtCantidad.getText();
        String categoria = (String) cboxCategoria.getSelectedItem();
        String descripcion= txtdescripcion.getText();
        String tipoProducto = (String) cboxTipoProducto.getSelectedItem();
        
       LocalDateTime fechaActual = LocalDateTime.now();
       
       if (tipoProducto == null || tipoProducto.equals("---SELECCIONA---")) {
            JOptionPane.showMessageDialog(this, "Selecciona si es Producto o Repuesto.");
            return;
        }
       if (categoria == null || categoria.equals("---SELECCIONA---")) {
            JOptionPane.showMessageDialog(this, "Seleccione la categoria.");
            return;
        }
       
        boolean registrado = inventario.agregarProducto(nombre, precio, cantidad, categoria, descripcion, tipoProducto, fechaActual);
        if (registrado) {
            txtNombre.setText("");
            txtPrecio.setText("");
            txtCantidad.setText("");
            txtdescripcion.setText("");
            cboxCategoria.setSelectedIndex(0);
            cboxTipoProducto.setSelectedIndex(0);
            mostrarInventario(); 
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Deseas ir al formulario de búsqueda de productos?",
        "Confirmación",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        FrmBusqueda frmBusqueda=new FrmBusqueda(this.inventario);
        frmBusqueda.setVisible(true);
    }
    
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

        mostrarInventario();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
     int filaSeleccionada = tablaInventario.getSelectedRow();

if (filaSeleccionada >= 0) {
    // Obtener el producto seleccionado (opcional, si deseas mostrar nombre en el mensaje de confirmación)
    Producto productoSeleccionado = inventario.getListaProductos().get(filaSeleccionada);
    
    // Confirmación antes de eliminar
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que deseas eliminar el producto: " + productoSeleccionado.getNombre() + "?",
        "Confirmar eliminación",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        // Eliminar del inventario
        inventario.getListaProductos().remove(filaSeleccionada);

        // Eliminar del modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaInventario.getModel();
        modelo.removeRow(filaSeleccionada);

        // Mensaje de éxito
        javax.swing.JOptionPane.showMessageDialog(this, "Producto eliminado con éxito.");
    }
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
}

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            FrmMenu FM= new FrmMenu();
            FM.setVisible(true);
            dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void filtrarPorCategoria() {
    String categoriaSeleccionada = (String) cboxCategoria.getSelectedItem();
    if (categoriaSeleccionada == null || categoriaSeleccionada.equals("---SELECCIONA---")) {
        mostrarInventario(); // Muestra todo si no hay categoría seleccionada
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) tablaInventario.getModel();
    modelo.setRowCount(0); // Limpiar tabla

    List<Producto> productos = inventario.getListaProductos();
    for (Producto p : productos) {
        if (categoriaSeleccionada.equalsIgnoreCase(p.getCategoria())) {
            Object[] fila = {
                p.getNombre(),
                p.getPrecio(),
                p.getCantidad(),
                p.getCategoria(),
                p.getDescripcion(),
                p.getFecha() != null ? p.getFecha().toString() : ""
            };
            modelo.addRow(fila);
        }
    }
}

    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada=tablaInventario.getSelectedRow();

        if(filaSeleccionada== -1){
            JOptionPane.showMessageDialog(this, "Seleccione el producto que desea editar");
            return;
        }
        Producto producto = inventario.getListaProductos().get(filaSeleccionada);

        String nuevoNombre = JOptionPane.showInputDialog(this, "Nuevo nombre:", producto.getNombre());
        String nuevoPrecioStr = JOptionPane.showInputDialog(this, "Nuevo precio:", producto.getPrecio());
        String nuevaCantidadStr = JOptionPane.showInputDialog(this, "Nueva cantidad:", producto.getCantidad());
        String nuevaDescripcion = JOptionPane.showInputDialog(this, "Nueva descripcion:", producto.getDescripcion());

        if (nuevoNombre != null && !nuevoNombre.trim().isEmpty() &&
    nuevoPrecioStr != null && !nuevoPrecioStr.trim().isEmpty() &&
    nuevaCantidadStr != null && !nuevaCantidadStr.trim().isEmpty() &&
    nuevaDescripcion != null && !nuevaDescripcion.trim().isEmpty()) {
            try {
                double nuevoPrecio = Double.parseDouble(nuevoPrecioStr);
                int nuevaCantidad = Integer.parseInt(nuevaCantidadStr);

                producto.setNombre(nuevoNombre);
                producto.setPrecio(nuevoPrecio);
                producto.setCantidad(nuevaCantidad);
                producto.setDescripcion(nuevaDescripcion);
                producto.setFecha(LocalDateTime.now());
                

                mostrarInventario();
                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Precio o cantidad inválidos.");
            }
        }else {
    JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados ,NO SE PERMITEN VALORES NULOS");
}
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        // TODO add your handling code here:
        String nuevaCategoria=JOptionPane.showInputDialog(this,"Ingrese el nombre de la nueva categoría: ");
        if(nuevaCategoria!=null && !nuevaCategoria.trim().isEmpty()){
            inventario.AgregarCategorias(nuevaCategoria.trim());
            actualizarComboCategoria();
            cboxCategoria.setSelectedItem(nuevaCategoria.trim());
            if(frmBusque!=null){
                frmBusque.actualizarComboCategorias();
            }
        }
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        // TODO add your handling code here:
        String categoriaActual=(String) cboxCategoria.getSelectedItem();
        if(categoriaActual==null||categoriaActual.equals("--SELECCIONA--")){
            JOptionPane.showMessageDialog(this, "Seleccione una categoria existente para editar");
            return;
        }
        
        String nuevaCategoria=JOptionPane.showInputDialog(this,"Ingrese el nuevo nombre para la categoria: ",categoriaActual);
        if(nuevaCategoria!=null && !nuevaCategoria.trim().isEmpty()){
            inventario.EditarCategoria(categoriaActual, nuevaCategoria.trim());
            actualizarComboCategoria();
            mostrarInventario();
            if(frmBusque!=null){
                frmBusque.actualizarComboCategorias();
            }
        }
    }//GEN-LAST:event_btnEditar2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        // TODO add your handling code here:
        String categoriaActual=(String) cboxCategoria.getSelectedItem();
        if(categoriaActual==null||categoriaActual.equals("--SELECCIONA--")){
            JOptionPane.showMessageDialog(this,"Seleccione la categoria para eliminar");
            return;
        }
        int confirmacion=JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar esta categoria  "+categoriaActual+"?",
                "Confirmar",JOptionPane.YES_NO_OPTION);
        if(confirmacion==JOptionPane.YES_OPTION){
            inventario.EliminarCategoria(categoriaActual);
            actualizarComboCategoria();
            if(frmBusque!=null){
                frmBusque.actualizarComboCategorias();
            }
        }
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void cboxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCategoriaActionPerformed

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void actualizarComboCategoria(){
        cboxCategoria.removeAllItems();
        cboxCategoria.addItem("---SELECCIONA---");
        for(Categoria c: inventario.getListaCategorias()){
            cboxCategoria.addItem(c.getNombre());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal(ControlInventario.getInventario()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboxCategoria;
    private javax.swing.JComboBox<String> cboxTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}

